# Generated by Django 3.2 on 2023-08-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product_size',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_size',
            name='size',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='order_product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
