# Generated by Django 3.2 on 2023-08-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_child',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_children', to='app.category'),
        ),
    ]
