# Generated by Django 3.2 on 2023-08-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_child_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='size',
            name='products',
            field=models.ManyToManyField(through='app.Product_size', to='app.Product'),
        ),
    ]
