# Generated by Django 3.2 on 2023-08-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
