# Generated by Django 3.2 on 2023-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='products',
            field=models.ManyToManyField(related_name='sizes', through='app.Product_size', to='app.Product'),
        ),
    ]
