# Generated by Django 3.2 on 2023-08-15 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_size_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
