# Generated by Django 3.2 on 2023-08-16 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(default='auth.User', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
