# Generated by Django 3.2 on 2023-08-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_order_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cart_item',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Category_child',
            new_name='CategoryChild',
        ),
        migrations.RenameModel(
            old_name='Product_size',
            new_name='ProductSize',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cart'),
        ),
        migrations.DeleteModel(
            name='Order_product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='app.product'),
        ),
    ]
